version: "3.3"
services: 
    mongodb:
        image: mongo:4.0.4
        container_name: mongo_cr
        environment: 
            - PUID=1000
            - PGID=1000
        volumes:
            - ./mongo_data:/data/db
        ports:
            - 27017:27017
        restart: unless-stopped

    nginx:
        image: nginx
        container_name: nginx_cr
        depends_on: 
            - mongodb
        volumes:
            - ./cr_records.conf:/etc/nginx/conf.d/default.conf
            - ./index.html:/usr/share/nginx/html/index.html
        ports:
            - "8081:80"
        restart: always
